### ISSUE TITLE
Only getting 500 Errors

### ISSUE THREAD

**Issue by Stanzilla** [ncla/SteamInventoryExpert#2]
Not sure if extension of Valve fault

```
http://steamcommunity.com/market/priceoverview/?appid=753&country=DE&currency=3&market_hash_name=257510-TALOS/SOMA Failed to load resource: the server responded with a status of 500 (Internal Server Error)

2016-06-10 21:20:12.729 http://steamcommunity.com/market/priceoverview/?appid=753&country=DE&currency=3&market_hash_name=257510-TALOS/SOMA%20(Trading%20Card) Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by ylms** [comment]
If you hit too much to VALVe's servers you will end up with temporary ban. The thing is VALVe limited to fetching prices from their servers.

**Comment by ncla** [comment]
IIRC you would be getting 429 HTTP status code instead if it's rate-limiting. But yeah, that endpoint is really strict, something like 15requests/minute.

**Comment by Stanzilla** [comment]
Okay, it's 400 (Bad Request) now

![chrome_2016-06-11_15-59-46](https://cloud.githubusercontent.com/assets/75278/15985449/9aaa6492-2fed-11e6-82df-440509db0d8a.png)

**Comment by ncla** [comment]
Does this happen with SIH 1.9.2?

**Comment by Stanzilla** [comment]
yes

**Comment by ncla** [comment]
There's a possibility Valve has tightened rate limits for market related requests even further
https://www.reddit.com/r/Steam/comments/4nl5sp/youve_made_too_many_requests_recently_please_wait/

**Comment by skyborgff** [comment]
What should i change in the code so that i could have more than 100 listings?
