### ISSUE TITLE
Extension Warning at every start of Chrome

### ISSUE THREAD

**Issue by Hrxn** [ncla/SteamInventoryExpert#8]
Related to #5 
But 'removing' might be misleading, so just FYI.

This is what I see when I start Chrome:
![1](https://cloud.githubusercontent.com/assets/12064918/18236520/2bf9e77a-7327-11e6-9e29-05dd91018678.jpg)

Enabling 'Developer Mode' in chrome://extensions does not change anything here.

Running latest Chrome stable (`53.0.2785.89 (64-bit)`) on Windows 10 x64.

**Comment by ncla** [comment]
AFAIK you can't get rid of it, I have had this all the time.

http://stackoverflow.com/questions/23055651/disable-developer-mode-extensions-pop-up
